version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fitness-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    networks:
      - fitness-net

networks:
  fitness-net:
    driver: bridge
